parent=keycloak
# (optional) pull shared assets/macros from the default
import=common/keycloak

# load our stylesheet
styles=css/styles.css

# (optional) expose a display name in the admin theme dropdown
locales=en
